using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NTypeForge.Variadic.SourceGenerator
{
    // Pure string building: turns an arity N into the variadic delegate family plus the N-ary
    // sequence combinators. Everything here is a deterministic function of N - no symbols, no
    // ambient state - so the generator's output is byte-stable across runs and machines.
    //
    // The whole point is to escape C#'s lack of variadic generics: one hand-written `Func<...>`
    // caps out at 16 type arguments, so a family that must "scale to an arbitrary number of
    // arguments" has to be stamped out per arity. We generate our own delegates (rather than reuse
    // `System.Func`) precisely so N is not bounded by the BCL's 16.
    internal static class VariadicEmitter
    {
        private const string Ienum = "global::System.Collections.Generic.IEnumerable";

        // The trigger/config attribute, emitted via post-initialization so a consumer can write
        // `[assembly: VariadicArity(N)]` without hand-authoring the type. It is `internal` so it
        // never leaks from the consumer's public surface.
        public const string AttributeSource =
@"// <auto-generated/>
#nullable enable
namespace NTypeForge.Variadic
{
    /// <summary>Sets the maximum arity N of the generated variadic delegates and combinators.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
    internal sealed class VariadicArityAttribute : global::System.Attribute
    {
        public VariadicArityAttribute(int maxArity) { MaxArity = maxArity; }
        public int MaxArity { get; }
    }
}
";

        public static string EmitAll(int maxArity)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace NTypeForge.Variadic");
            sb.AppendLine("{");

            for (int n = 1; n <= maxArity; n++) EmitFunc(sb, n);
            sb.AppendLine();
            for (int n = 1; n <= maxArity; n++) EmitAction(sb, n);
            sb.AppendLine();

            sb.AppendLine("    // N-ary sequence combinators. Zip starts at arity 3 because the BCL already");
            sb.AppendLine("    // provides a 2-sequence Enumerable.Zip(..., Func<,,>) (a plain `using System.Linq;`");
            sb.AppendLine("    // would make a 2-ary overload here ambiguous); ForEach has no BCL counterpart, so");
            sb.AppendLine("    // it starts at 2.");
            sb.AppendLine("    public static class VariadicEnumerable");
            sb.AppendLine("    {");
            for (int n = 3; n <= maxArity; n++) EmitZip(sb, n);
            for (int n = 2; n <= maxArity; n++) EmitForEach(sb, n);
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }

        // public delegate TResult VariadicFunc<in T1, ..., in Tn, out TResult>(T1 arg1, ..., Tn argn);
        private static void EmitFunc(StringBuilder sb, int n)
        {
            var tparams = Enumerable.Range(1, n).Select(i => "in T" + i).ToList();
            tparams.Add("out TResult");
            sb.AppendLine($"    // A function of {n} argument{Plural(n)} returning TResult.");
            sb.AppendLine($"    public delegate TResult VariadicFunc<{string.Join(", ", tparams)}>({Params(n)});");
        }

        // public delegate void VariadicAction<in T1, ..., in Tn>(T1 arg1, ..., Tn argn);
        private static void EmitAction(StringBuilder sb, int n)
        {
            var tparams = Enumerable.Range(1, n).Select(i => "in T" + i);
            sb.AppendLine($"    // An action of {n} argument{Plural(n)}.");
            sb.AppendLine($"    public delegate void VariadicAction<{string.Join(", ", tparams)}>({Params(n)});");
        }

        // A Zip over n sequences: a public extension that eagerly null-checks and hands off to a
        // deferred iterator, so a null argument throws at the call site rather than on enumeration.
        private static void EmitZip(StringBuilder sb, int n)
        {
            var tArgs = TypeArgs(n);
            var selector = $"VariadicFunc<{tArgs}, TResult> selector";

            sb.AppendLine($"        // Combines {n} sequences element-wise until the shortest is exhausted.");
            sb.AppendLine($"        public static {Ienum}<TResult> Zip<{tArgs}, TResult>(");
            sb.AppendLine($"            {ExtSourceParams(n)}, {selector})");
            sb.AppendLine("        {");
            EmitNullChecks(sb, n, "selector");
            sb.AppendLine($"            return ZipIterator({SourceArgs(n)}, selector);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static {Ienum}<TResult> ZipIterator<{tArgs}, TResult>(");
            sb.AppendLine($"            {SourceParams(n)}, {selector})");
            sb.AppendLine("        {");
            EmitEnumerators(sb, n);
            sb.AppendLine($"            while ({MoveNextAll(n)})");
            sb.AppendLine($"                yield return selector({Currents(n)});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // A ForEach over n sequences: eager (no deferral needed), so the whole body is one method.
        private static void EmitForEach(StringBuilder sb, int n)
        {
            var tArgs = TypeArgs(n);

            sb.AppendLine($"        // Invokes action on the element-wise tuples of {n} sequences until the shortest ends.");
            sb.AppendLine($"        public static void ForEach<{tArgs}>(");
            sb.AppendLine($"            {ExtSourceParams(n)}, VariadicAction<{tArgs}> action)");
            sb.AppendLine("        {");
            EmitNullChecks(sb, n, "action");
            EmitEnumerators(sb, n);
            sb.AppendLine($"            while ({MoveNextAll(n)})");
            sb.AppendLine($"                action({Currents(n)});");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitNullChecks(StringBuilder sb, int n, string delegateParam)
        {
            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            if (source{i} is null) throw new global::System.ArgumentNullException(nameof(source{i}));");
            sb.AppendLine($"            if ({delegateParam} is null) throw new global::System.ArgumentNullException(nameof({delegateParam}));");
        }

        private static void EmitEnumerators(StringBuilder sb, int n)
        {
            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            using var e{i} = source{i}.GetEnumerator();");
        }

        // --- tiny shape helpers, all pure functions of the arity ---
        private static string Plural(int n) => n == 1 ? "" : "s";
        private static string Params(int n) => Join(n, i => $"T{i} arg{i}");
        private static string TypeArgs(int n) => Join(n, i => "T" + i);
        private static string SourceParams(int n) => Join(n, i => $"{Ienum}<T{i}> source{i}");
        private static string ExtSourceParams(int n) => Join(n, i => $"{(i == 1 ? "this " : "")}{Ienum}<T{i}> source{i}");
        private static string SourceArgs(int n) => Join(n, i => "source" + i);
        private static string MoveNextAll(int n) => string.Join(" && ", Enumerable.Range(1, n).Select(i => $"e{i}.MoveNext()"));
        private static string Currents(int n) => Join(n, i => $"e{i}.Current");

        private static string Join(int n, System.Func<int, string> project)
            => string.Join(", ", Enumerable.Range(1, n).Select(project));
    }
}
