using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using NTypeForge.SourceGenerator.Models;

namespace NTypeForge.SourceGenerator
{
    // Output stage (symbol-free): renders proxy classes and the per-target extension class from the
    // equatable models. The match map and interface requirements are held as fields so the many
    // emit helpers don't have to thread them through every call.
    internal sealed class ProxyEmitter
    {
        private readonly Dictionary<string, List<ConcreteInfo>> _possibleMatches;
        private readonly Dictionary<string, InterfaceInfo> _interfaceInfo;

        public ProxyEmitter(
            Dictionary<string, List<ConcreteInfo>> possibleMatches,
            Dictionary<string, InterfaceInfo> interfaceInfo)
        {
            _possibleMatches = possibleMatches;
            _interfaceInfo = interfaceInfo;
        }

        public void Emit(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            EmitProxies(context, allExtensions);
            EmitExtensions(context, allExtensions);
        }

        private void EmitProxies(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var proxiesByNamespace = new Dictionary<string, List<ProxyDecl>>(StringComparer.Ordinal);
            var added = new HashSet<string>(StringComparer.Ordinal);

            void AddProxy(string uFq, string uNs, string uMin, string iFq, string iMin,
                IReadOnlyList<MethodSig> mReqs,
                IReadOnlyList<PropertySig> pReqs,
                IReadOnlyList<IndexerSig> iReqs,
                IReadOnlyList<EventSig> eReqs)
            {
                if (!added.Add(uFq + "|" + iFq)) return;
                if (!proxiesByNamespace.TryGetValue(uNs, out var list))
                {
                    list = new List<ProxyDecl>();
                    proxiesByNamespace[uNs] = list;
                }
                list.Add(new ProxyDecl(uFq, uNs, uMin, iFq, iMin, mReqs, pReqs, iReqs, eReqs));
            }

            foreach (var item in allExtensions)
            {
                AddProxy(item.UnderlyingFq, item.UnderlyingNamespace, item.UnderlyingMinimalName,
                    item.InterfaceFq, item.InterfaceMinimalName,
                    item.MethodRequirements, item.PropertyRequirements, item.IndexerRequirements, item.EventRequirements);
            }
            foreach (var kvp in _possibleMatches)
            {
                var iface = _interfaceInfo[kvp.Key];
                foreach (var concrete in kvp.Value)
                {
                    AddProxy(concrete.Fq, concrete.Namespace, concrete.MinimalName,
                        iface.Fq, iface.MinimalName,
                        iface.MethodRequirements, iface.PropertyRequirements, iface.IndexerRequirements, iface.EventRequirements);
                }
            }

            foreach (var kvp in proxiesByNamespace.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {kvp.Key}");
                sb.AppendLine("{");
                foreach (var proxy in kvp.Value.OrderBy(x => x.UnderlyingFq + "|" + x.InterfaceFq, StringComparer.Ordinal))
                {
                    GenerateProxy(sb, proxy);
                }
                sb.AppendLine("}");
                // Hash-suffix the hint: two namespaces can sanitize to the same identifier (e.g.
                // `A.B` and `A_B`), which would otherwise produce a duplicate hint name and crash
                // the generator.
                context.AddSource($"{Sanitize(kvp.Key)}_Proxies_{StableHash(kvp.Key)}.g.cs", sb.ToString());
            }
        }

        private void EmitExtensions(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var extensionsByTarget = new Dictionary<string, List<CandidateModel>>(StringComparer.Ordinal);
            foreach (var item in allExtensions)
            {
                if (!extensionsByTarget.TryGetValue(item.TargetFq, out var list))
                {
                    list = new List<CandidateModel>();
                    extensionsByTarget[item.TargetFq] = list;
                }
                list.Add(item);
            }

            foreach (var kvp in extensionsByTarget.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                // Order by a location-independent content key so the emitted Duck<T> branches and
                // forwarding methods don't depend on the order the duck sites appear in source.
                var items = kvp.Value.OrderBy(EmitOrderKey, StringComparer.Ordinal).ToList();
                var first = items[0];
                var targetNamespace = first.TargetNamespace;
                var targetFullName = first.TargetFq;
                // Hash-suffix by the target's fully-qualified name: two distinct targets in one
                // namespace can share a sanitized minimal name, which would collide as a public class
                // name (CS0101). The class is an implementation detail (found via its `extension`
                // receiver, never referenced by name), so the suffix is harmless.
                var extensionClassName = $"{Sanitize(first.TargetMinimalName)}_DuckTypingExtensions_{StableHash(targetFullName)}";

                // The extension receiver name must not collide with any forwarding method's
                // parameter (which carry user-chosen names), or the generated code fails CS0136.
                var forwardingParamNames = new HashSet<string>(
                    items.Where(c => !c.IsDuckCall).SelectMany(c => c.OriginalParameters.Select(p => p.Name)),
                    StringComparer.Ordinal);
                var receiver = SafeIdent("target", forwardingParamNames);

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {targetNamespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class {extensionClassName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        extension ({targetFullName} {receiver})");
                sb.AppendLine("        {");

                EmitDuckMethod(sb, items, receiver);
                EmitForwardingMethods(sb, items, targetFullName, receiver);

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                // The class name already carries the target's FQ hash, so the hint is unique per
                // target (and across namespaces that sanitize alike).
                context.AddSource($"{Sanitize(targetNamespace)}_{extensionClassName}.g.cs", sb.ToString());
            }
        }

        // Stable, location-independent ordering key for a candidate's emitted contribution: the
        // forwarded method name + parameter shape, then the interface and underlying types. Duck
        // calls (empty method name / parameters) collapse to ordering by interface.
        private static string EmitOrderKey(CandidateModel c)
            => string.Join("|",
                c.OriginalMethodName,
                string.Join(",", c.OriginalParameters.Select(p => p.Key)),
                c.ArgumentFq,
                c.InterfaceFq,
                c.UnderlyingFq);

        // Emit a single Duck<T>() per target type that dispatches on typeof(T). One method per
        // interface would share the identical Duck<T>() signature (return type and generic
        // constraints don't participate in overloading) and collide with CS0111 when a type is
        // ducked to more than one interface.
        private void EmitDuckMethod(StringBuilder sb, List<CandidateModel> items, string receiver)
        {
            var duckCandidates = new List<CandidateModel>();
            var seenDuckInterfaces = new HashSet<string>(StringComparer.Ordinal);
            foreach (var item in items)
            {
                if (item.IsDuckCall && seenDuckInterfaces.Add(item.InterfaceFq))
                    duckCandidates.Add(item);
            }

            if (duckCandidates.Count == 0) return;

            sb.AppendLine("            public T Duck<T>() where T : class");
            sb.AppendLine("            {");
            foreach (var candidate in duckCandidates)
            {
                var iface = candidate.InterfaceFq;
                sb.AppendLine($"                if (typeof(T) == typeof({iface}))");
                sb.AppendLine("                {");
                // Unwrap check: only when target is an interface can it actually be a proxy that
                // needs re-wrapping. For a concrete target the unwrap branch is always trivially
                // taken, so we skip it and wrap directly.
                if (candidate.TargetIsInterface && _possibleMatches.TryGetValue(iface, out var matches))
                {
                    int ui = 0;
                    foreach (var m in matches)
                    {
                        var local = $"__ntf_c{ui++}";
                        sb.AppendLine($"                    if ({receiver}.TryUnbox<{m.Fq}>(out var {local})) return (T)(object)new {ProxyFullName(m.Namespace, m.MinimalName, m.Fq, candidate.InterfaceMinimalName, candidate.InterfaceFq)}({local});");
                    }
                }
                // Direct wrap. Unreachable for a proxy whose concrete type was ducked in this
                // compilation (its TryUnbox branch above wins). It only fires for a non-proxy or
                // for a proxy whose concrete is unknown here (e.g. created in another assembly); in
                // the latter case this double-wraps, but TryUnbox/Unbox still walk the full chain
                // back to the original instance, so only single-level IProxy<T>.Inner is affected.
                sb.AppendLine($"                    return (T)(object)new {ProxyFullName(candidate.UnderlyingNamespace, candidate.UnderlyingMinimalName, candidate.UnderlyingFq, candidate.InterfaceMinimalName, candidate.InterfaceFq)}(({candidate.UnderlyingFq}){receiver});");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                throw new global::System.InvalidOperationException(\"NTypeForge: no proxy was generated for \" + typeof(T));");
            sb.AppendLine("            }");
        }

        private void EmitForwardingMethods(StringBuilder sb, List<CandidateModel> items, string targetFullName, string receiver)
        {
            var generatedMethods = new HashSet<string>(StringComparer.Ordinal);

            foreach (var candidate in items)
            {
                if (candidate.IsDuckCall) continue;
                EmitForwardingMethod(sb, candidate, targetFullName, receiver, generatedMethods);
            }
        }

        private void EmitForwardingMethod(
            StringBuilder sb, CandidateModel candidate, string targetFullName, string receiver, HashSet<string> generatedMethods)
        {
            var argIndex = candidate.ArgumentIndex;
            var parameters = candidate.OriginalParameters;
            var argName = SymbolNames.Escape(parameters[argIndex].Name);
            var callReceiver = candidate.IsStatic ? targetFullName : receiver;
            var methodName = SymbolNames.Escape(candidate.OriginalMethodName);

            // The forwarding call's argument list, with the duck-typed argument replaced by
            // `argReplacement` and every other parameter passed through verbatim.
            string CallArgs(string argReplacement) => string.Join(", ", parameters.Select((p, idx) =>
                idx == argIndex ? argReplacement : $"{RefPrefix(p.RefKind)}{SymbolNames.Escape(p.Name)}"));

            var methodParams = string.Join(", ", parameters.Select((p, idx) =>
                $"{RefPrefix(p.RefKind)}{(idx == argIndex ? candidate.ArgumentFq : p.TypeFq)} {SymbolNames.Escape(p.Name)}"));

            var methodSig = $"{methodName}({methodParams})";
            if (!generatedMethods.Add(methodSig)) return;

            // Unwrap locals must not collide with this method's parameters or the receiver.
            var taken = new HashSet<string>(parameters.Select(p => SymbolNames.Escape(p.Name)), StringComparer.Ordinal) { receiver };
            var localPrefix = SafeLocalPrefix(taken);

            var isStatic = candidate.IsStatic ? "static " : "";
            sb.AppendLine($"            public {isStatic}{candidate.OriginalReturnTypeFq} {methodName}({methodParams})");
            sb.AppendLine("            {");

            EmitForwardingUnwrapBranches(sb, candidate, argName, callReceiver, methodName, CallArgs, localPrefix);

            // Direct wrap fallback; see the note in EmitDuckMethod for the cross-assembly
            // double-wrap boundary (recoverable via TryUnbox/Unbox).
            var directProxy = ProxyFullName(candidate.UnderlyingNamespace, candidate.UnderlyingMinimalName, candidate.UnderlyingFq, candidate.InterfaceMinimalName, candidate.InterfaceFq);
            var directCall = $"{callReceiver}.{methodName}({CallArgs($"new {directProxy}(({candidate.UnderlyingFq}){argName})")})";
            sb.AppendLine($"                {ReturnStatement(candidate.OriginalReturnsVoid, directCall)}");
            sb.AppendLine("            }");
        }

        private void EmitForwardingUnwrapBranches(
            StringBuilder sb, CandidateModel candidate, string argName, string receiver, string methodName,
            Func<string, string> callArgs, string localPrefix)
        {
            // Unwrap branches only make sense when the incoming value can actually be a proxy, i.e.
            // when its static type is an interface. For a concrete argument type they are dead
            // branches and force a needless box, so we skip straight to the direct wrap.
            if (!candidate.ArgumentIsInterface || !_possibleMatches.TryGetValue(candidate.InterfaceFq, out var matches))
                return;

            int ui = 0;
            foreach (var m in matches)
            {
                var local = $"{localPrefix}{ui++}";
                var proxy = ProxyFullName(m.Namespace, m.MinimalName, m.Fq, candidate.InterfaceMinimalName, candidate.InterfaceFq);
                var call = $"{receiver}.{methodName}({callArgs($"new {proxy}({local})")})";
                sb.AppendLine($"                if ({argName}.TryUnbox<{m.Fq}>(out var {local})) {{");
                sb.AppendLine($"                    {(candidate.OriginalReturnsVoid ? $"{call}; return;" : $"return {call};")}");
                sb.AppendLine("                }");
            }
        }

        private static void GenerateProxy(StringBuilder sb, ProxyDecl proxy)
        {
            var structName = GetProxyStructName(proxy.UnderlyingMinimalName, proxy.UnderlyingFq, proxy.InterfaceMinimalName, proxy.InterfaceFq);
            var interfaceFullName = proxy.InterfaceFq;
            var underlyingFullName = proxy.UnderlyingFq;

            // A `class`, not a `readonly struct`. A struct proxy is boxed the instant it's passed as
            // the interface, so it allocates anyway - while making a struct *underlying* impossible to
            // proxy correctly: a settable property/indexer would emit `__ntf_instance.X = value`
            // against a readonly value-type field (CS1648), and every mutating call would hit a fresh
            // defensive copy, silently losing state. A class with a mutable field allocates the same
            // (one object per call) and keeps the wrapped instance consistent for its whole lifetime.
            sb.AppendLine($"    internal sealed class {structName} : {interfaceFullName}, IProxy<{underlyingFullName}>");
            sb.AppendLine("    {");
            // Not `readonly`: a struct underlying must stay mutable so `__ntf_instance.X = value` and
            // mutating methods compile and take effect (CS1648 otherwise).
            sb.AppendLine($"        private {underlyingFullName} __ntf_instance;");
            sb.AppendLine();
            sb.AppendLine($"        public {structName}({underlyingFullName} instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            __ntf_instance = instance;");
            sb.AppendLine("        }");
            sb.AppendLine();
            // IProxy members are implemented explicitly so they never collide with an interface
            // member that happens to be named `Inner` or `Unwrapped`.
            sb.AppendLine($"        {underlyingFullName} IProxy<{underlyingFullName}>.Inner => __ntf_instance;");
            sb.AppendLine($"        object IProxy.Unwrapped => __ntf_instance;");
            sb.AppendLine();

            foreach (var method in proxy.MethodRequirements) EmitProxyMethod(sb, method);
            foreach (var prop in proxy.PropertyRequirements) EmitProxyProperty(sb, prop);
            foreach (var idx in proxy.IndexerRequirements) EmitProxyIndexer(sb, idx);
            foreach (var evt in proxy.EventRequirements) EmitProxyEvent(sb, evt);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitProxyMethod(StringBuilder sb, MethodSig method)
        {
            var name = SymbolNames.Escape(method.Name);
            var typeParams = method.Arity > 0 ? $"<{string.Join(", ", method.TypeParameters)}>" : "";
            var parametersStr = string.Join(", ", method.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{p.TypeFq} {SymbolNames.Escape(p.Name)}"));
            var argsStr = string.Join(", ", method.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{SymbolNames.Escape(p.Name)}"));

            sb.AppendLine($"        public {method.ReturnTypeFq} {name}{typeParams}({parametersStr})");
            foreach (var constraint in method.Constraints)
            {
                if (!string.IsNullOrEmpty(constraint)) sb.AppendLine($"            {constraint}");
            }
            sb.AppendLine("        {");
            sb.AppendLine($"            {ReturnStatement(method.ReturnsVoid, $"__ntf_instance.{name}{typeParams}({argsStr})")}");
            sb.AppendLine("        }");
        }

        private static void EmitProxyProperty(StringBuilder sb, PropertySig prop)
        {
            var name = SymbolNames.Escape(prop.Name);
            sb.AppendLine($"        public {prop.TypeFq} {name}");
            sb.AppendLine("        {");
            if (prop.HasGet) sb.AppendLine($"            get => __ntf_instance.{name};");
            // Match the interface's accessor kind: an `init`-only property must be implemented with
            // `init` (CS8854 otherwise). Structural matching guarantees the underlying has a regular
            // `set` here, so forwarding `__ntf_instance.X = value` is legal.
            if (prop.HasSet) sb.AppendLine($"            {(prop.IsInit ? "init" : "set")} => __ntf_instance.{name} = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyIndexer(StringBuilder sb, IndexerSig idx)
        {
            // Indexers are positional, so the proxy renames the parameters to safe generated names.
            // This sidesteps every parameter-name hazard at once: a keyword (`@int`), a name that
            // collides with the setter's implicit `value`, etc.
            var names = idx.Parameters.Select((_, i) => $"__ntf_a{i}").ToList();
            var parametersStr = string.Join(", ", idx.Parameters.Select((p, i) => $"{RefPrefix(p.RefKind)}{p.TypeFq} {names[i]}"));
            var argsStr = string.Join(", ", idx.Parameters.Select((p, i) => $"{RefPrefix(p.RefKind)}{names[i]}"));
            sb.AppendLine($"        public {idx.TypeFq} this[{parametersStr}]");
            sb.AppendLine("        {");
            if (idx.HasGet) sb.AppendLine($"            get => __ntf_instance[{argsStr}];");
            if (idx.HasSet) sb.AppendLine($"            set => __ntf_instance[{argsStr}] = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyEvent(StringBuilder sb, EventSig evt)
        {
            var name = SymbolNames.Escape(evt.Name);
            sb.AppendLine($"        public event {evt.TypeFq} {name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            add => __ntf_instance.{name} += value;");
            sb.AppendLine($"            remove => __ntf_instance.{name} -= value;");
            sb.AppendLine("        }");
        }

        // ---------------------------------------------------------------------------------------
        // Pure string helpers
        // ---------------------------------------------------------------------------------------

        // global::-qualified so a proxy reference can never be mistaken for a member of a like-named
        // namespace, type, or (e.g.) the surrounding Duck<T> type parameter.
        private static string ProxyFullName(
            string underlyingNamespace, string underlyingMinimalName, string underlyingFq,
            string interfaceMinimalName, string interfaceFq)
            => $"global::{underlyingNamespace}.{GetProxyStructName(underlyingMinimalName, underlyingFq, interfaceMinimalName, interfaceFq)}";

        private static string RefPrefix(RefKind refKind)
            => refKind switch { RefKind.Ref => "ref ", RefKind.Out => "out ", RefKind.In => "in ", _ => "" };

        // A generated identifier (e.g. the extension receiver) that does not collide with any
        // user-derived name in `taken`; prepends `_` until unique. Normally returns `desired`.
        private static string SafeIdent(string desired, ICollection<string> taken)
        {
            var name = desired;
            while (taken.Contains(name)) name = "_" + name;
            return name;
        }

        // A prefix for generated locals emitted as `{prefix}0`, `{prefix}1`, ... that no name in
        // `taken` collides with. The `__ntf_c` base is already collision-resistant; the loop makes
        // it bulletproof.
        private static string SafeLocalPrefix(ICollection<string> taken)
        {
            var prefix = "__ntf_c";
            while (taken.Any(n => n.StartsWith(prefix, StringComparison.Ordinal) && n.Length > prefix.Length && char.IsDigit(n[prefix.Length])))
                prefix = "_" + prefix;
            return prefix;
        }

        private static string ReturnStatement(bool returnsVoid, string call)
            => returnsVoid ? $"{call};" : $"return {call};";

        // Maps an arbitrary type display name to a valid C# identifier fragment: every character
        // that isn't a letter, digit, or underscore becomes '_', and a leading digit is prefixed.
        // This keeps generic/array/nested type names (e.g. `Holder<int, string>`) from producing
        // illegal struct names.
        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name)) return "_";
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        // Readable prefix (minimal names) plus a stable hash of the fully-qualified underlying and
        // interface. The prefix aids debugging; the hash guarantees uniqueness, since distinct types
        // can sanitize to the same identifier (e.g. `Foo<int>` and a type literally named `Foo_int_`,
        // or nested `Outer.Inner` and `Outer_Inner`) and would otherwise collide (CS0101).
        private static string GetProxyStructName(
            string underlyingMinimalName, string underlyingFq, string interfaceMinimalName, string interfaceFq)
            => $"{Sanitize(underlyingMinimalName)}_{Sanitize(interfaceMinimalName)}_Proxy_{StableHash(underlyingFq + "|" + interfaceFq)}";

        // A deterministic 32-bit FNV-1a hash rendered as hex. string.GetHashCode is randomized per
        // process, which would break the generator's required determinism; this is stable across
        // runs and platforms.
        private static string StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261;
                foreach (var c in value)
                {
                    hash ^= c;
                    hash *= 16777619;
                }
                return hash.ToString("x8");
            }
        }
    }
}
