using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using NTypeForge.SourceGenerator.Models;

namespace NTypeForge.SourceGenerator
{
    // Output stage (symbol-free): renders proxy classes and the per-target extension class from the
    // equatable models. The match map and interface requirements are held as fields so the many
    // emit helpers don't have to thread them through every call.
    internal sealed class ProxyEmitter
    {
        private readonly Dictionary<string, List<ConcreteInfo>> _possibleMatches;
        private readonly Dictionary<string, InterfaceInfo> _interfaceInfo;

        public ProxyEmitter(
            Dictionary<string, List<ConcreteInfo>> possibleMatches,
            Dictionary<string, InterfaceInfo> interfaceInfo)
        {
            _possibleMatches = possibleMatches;
            _interfaceInfo = interfaceInfo;
        }

        public void Emit(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            EmitProxies(context, allExtensions);
            EmitExtensions(context, allExtensions);
        }

        private void EmitProxies(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var proxiesByNamespace = new Dictionary<string, List<ProxyDecl>>(StringComparer.Ordinal);
            var added = new HashSet<string>(StringComparer.Ordinal);

            void AddProxy(string uFq, string uNs, string uMin, string iFq, string iMin,
                IReadOnlyList<MethodSig> mReqs,
                IReadOnlyList<PropertySig> pReqs,
                IReadOnlyList<IndexerSig> iReqs,
                IReadOnlyList<EventSig> eReqs)
            {
                if (!added.Add(uFq + "|" + iFq)) return;
                if (!proxiesByNamespace.TryGetValue(uNs, out var list))
                {
                    list = new List<ProxyDecl>();
                    proxiesByNamespace[uNs] = list;
                }
                list.Add(new ProxyDecl(uFq, uNs, uMin, iFq, iMin, mReqs, pReqs, iReqs, eReqs));
            }

            foreach (var item in allExtensions)
            {
                foreach (var arg in item.DuckedArgs)
                {
                    AddProxy(arg.UnderlyingFq, arg.UnderlyingNamespace, arg.UnderlyingMinimalName,
                        arg.InterfaceFq, arg.InterfaceMinimalName,
                        arg.MethodRequirements, arg.PropertyRequirements, arg.IndexerRequirements, arg.EventRequirements);
                }
            }
            foreach (var kvp in _possibleMatches)
            {
                var iface = _interfaceInfo[kvp.Key];
                foreach (var concrete in kvp.Value)
                {
                    AddProxy(concrete.Fq, concrete.Namespace, concrete.MinimalName,
                        iface.Fq, iface.MinimalName,
                        iface.MethodRequirements, iface.PropertyRequirements, iface.IndexerRequirements, iface.EventRequirements);
                }
            }

            foreach (var kvp in proxiesByNamespace.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                context.CancellationToken.ThrowIfCancellationRequested();

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {kvp.Key}");
                sb.AppendLine("{");
                foreach (var proxy in kvp.Value.OrderBy(x => x.UnderlyingFq + "|" + x.InterfaceFq, StringComparer.Ordinal))
                {
                    GenerateProxy(sb, proxy);
                }
                sb.AppendLine("}");
                // Hash-suffix the hint: two namespaces can sanitize to the same identifier (e.g.
                // `A.B` and `A_B`), which would otherwise produce a duplicate hint name and crash
                // the generator.
                context.AddSource($"{Sanitize(kvp.Key)}_Proxies_{StableHash(kvp.Key)}.g.cs", sb.ToString());
            }
        }

        private void EmitExtensions(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var extensionsByTarget = new Dictionary<string, List<CandidateModel>>(StringComparer.Ordinal);
            foreach (var item in allExtensions)
            {
                if (!extensionsByTarget.TryGetValue(item.TargetFq, out var list))
                {
                    list = new List<CandidateModel>();
                    extensionsByTarget[item.TargetFq] = list;
                }
                list.Add(item);
            }

            foreach (var kvp in extensionsByTarget.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                context.CancellationToken.ThrowIfCancellationRequested();

                // Order by a location-independent content key so the emitted Duck<T> branches and
                // forwarding methods don't depend on the order the duck sites appear in source.
                var items = kvp.Value.OrderBy(EmitOrderKey, StringComparer.Ordinal).ToList();
                var first = items[0];
                var targetNamespace = first.TargetNamespace;
                var targetFullName = first.TargetFq;
                // Hash-suffix by the target's fully-qualified name: two distinct targets in one
                // namespace can share a sanitized minimal name, which would collide as a public class
                // name (CS0101). The class is an implementation detail (found via its `extension`
                // receiver, never referenced by name), so the suffix is harmless.
                var extensionClassName = $"{Sanitize(first.TargetMinimalName)}_DuckTypingExtensions_{StableHash(targetFullName)}";

                // The extension receiver name must not collide with any forwarding method's
                // parameter (which carry user-chosen names), or the generated code fails CS0136.
                var forwardingParamNames = new HashSet<string>(
                    items.Where(c => !c.IsDuckCall).SelectMany(c => c.OriginalParameters.Select(p => p.Name)),
                    StringComparer.Ordinal);
                var receiver = SafeIdent("target", forwardingParamNames);

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {targetNamespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    {(first.TargetIsPublic ? "public" : "internal")} static class {extensionClassName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        extension ({targetFullName} {receiver})");
                sb.AppendLine("        {");

                EmitDuckMethod(sb, items, receiver);
                EmitForwardingMethods(sb, items, targetFullName, receiver);

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                // The class name already carries the target's FQ hash, so the hint is unique per
                // target (and across namespaces that sanitize alike).
                context.AddSource($"{Sanitize(targetNamespace)}_{extensionClassName}.g.cs", sb.ToString());
            }
        }

        // Stable, location-independent ordering key for a candidate's emitted contribution: the
        // forwarded method name + parameter shape, then each ducked argument's static, interface,
        // and underlying types. Duck calls (empty method name / parameters) collapse to ordering
        // by interface.
        private static string EmitOrderKey(CandidateModel c)
            => string.Join("|",
                c.OriginalMethodName,
                string.Join(",", c.OriginalParameters.Select(p => p.Key)),
                string.Join(",", c.DuckedArgs.Select(a => $"{a.ArgumentFq}+{a.InterfaceFq}+{a.UnderlyingFq}")));

        // Emit a single Duck<T>() per target type that dispatches on typeof(T). One method per
        // interface would share the identical Duck<T>() signature (return type and generic
        // constraints don't participate in overloading) and collide with CS0111 when a type is
        // ducked to more than one interface.
        private void EmitDuckMethod(StringBuilder sb, List<CandidateModel> items, string receiver)
        {
            // A Duck<T> site always ducks exactly one argument: the receiver.
            var duckCandidates = new List<(CandidateModel Candidate, DuckedArgModel Arg)>();
            var seenDuckInterfaces = new HashSet<string>(StringComparer.Ordinal);
            foreach (var item in items)
            {
                if (item.IsDuckCall && seenDuckInterfaces.Add(item.DuckedArgs[0].InterfaceFq))
                    duckCandidates.Add((item, item.DuckedArgs[0]));
            }

            if (duckCandidates.Count == 0) return;

            sb.AppendLine("            public T Duck<T>() where T : class");
            sb.AppendLine("            {");
            foreach (var (candidate, arg) in duckCandidates)
            {
                var iface = arg.InterfaceFq;
                sb.AppendLine($"                if (typeof(T) == typeof({iface}))");
                sb.AppendLine("                {");
                // Unwrap check: only when target is an interface can it actually be a proxy that
                // needs re-wrapping. For a concrete target the unwrap branch is always trivially
                // taken, so we skip it and wrap directly.
                if (candidate.TargetIsInterface && _possibleMatches.TryGetValue(iface, out var matches))
                {
                    int ui = 0;
                    foreach (var m in matches)
                    {
                        var local = $"__ntf_c{ui++}";
                        sb.AppendLine($"                    if ({receiver}.TryUnbox<{m.Fq}>(out var {local})) return (T)(object)new {ProxyFullName(m.Namespace, m.MinimalName, m.Fq, arg.InterfaceMinimalName, arg.InterfaceFq)}({local});");
                    }
                }
                // Direct wrap. Unreachable for a proxy whose concrete type was ducked in this
                // compilation (its TryUnbox branch above wins). It only fires for a non-proxy or
                // for a proxy whose concrete is unknown here (e.g. created in another assembly); in
                // the latter case this double-wraps, but TryUnbox/Unbox still walk the full chain
                // back to the original instance, so only single-level IProxy<T>.Inner is affected.
                sb.AppendLine($"                    return (T)(object)new {ProxyFullName(arg.UnderlyingNamespace, arg.UnderlyingMinimalName, arg.UnderlyingFq, arg.InterfaceMinimalName, arg.InterfaceFq)}(({arg.UnderlyingFq}){receiver});");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                throw new global::System.InvalidOperationException(\"NTypeForge: no proxy was generated for \" + typeof(T));");
            sb.AppendLine("            }");
        }

        private void EmitForwardingMethods(StringBuilder sb, List<CandidateModel> items, string targetFullName, string receiver)
        {
            var generatedMethods = new HashSet<string>(StringComparer.Ordinal);

            foreach (var candidate in items)
            {
                if (candidate.IsDuckCall) continue;
                EmitForwardingMethod(sb, candidate, targetFullName, receiver, generatedMethods);
            }
        }

        private void EmitForwardingMethod(
            StringBuilder sb, CandidateModel candidate, string targetFullName, string receiver, HashSet<string> generatedMethods)
        {
            var parameters = candidate.OriginalParameters;
            var duckedByIndex = candidate.DuckedArgs.ToDictionary(a => a.ArgumentIndex);
            var methodName = SymbolNames.Escape(candidate.OriginalMethodName);
            var typeParams = candidate.OriginalArity > 0 ? $"<{string.Join(", ", candidate.OriginalTypeParameters)}>" : "";

            var methodParams = string.Join(", ", parameters.Select((p, idx) =>
                $"{ParamsPrefix(p)}{RefPrefix(p.RefKind)}{(duckedByIndex.TryGetValue(idx, out var ducked) ? ducked.ArgumentFq : p.TypeFq)} {SymbolNames.Escape(p.Name)}{DefaultSuffix(p)}"));

            var methodSig = $"{methodName}{typeParams}({methodParams})";
            if (!generatedMethods.Add(methodSig)) return;

            var isStatic = candidate.IsStatic ? "static " : "";
            sb.AppendLine($"            public {isStatic}{candidate.OriginalReturnTypeFq} {methodName}{typeParams}({methodParams})");
            foreach (var constraint in candidate.OriginalConstraints)
            {
                if (!string.IsNullOrEmpty(constraint)) sb.AppendLine($"                {constraint}");
            }
            sb.AppendLine("            {");
            if (candidate.DuckedArgs.Count == 1)
                EmitSingleArgForwardingBody(sb, candidate, targetFullName, receiver, methodName, typeParams);
            else
                EmitMultiArgForwardingBody(sb, candidate, targetFullName, receiver, methodName, typeParams);
            sb.AppendLine("            }");
        }

        // One ducked argument: each unwrap branch returns the forwarded call directly, with the
        // direct wrap as the unconditional fall-through.
        private void EmitSingleArgForwardingBody(
            StringBuilder sb, CandidateModel candidate, string targetFullName, string receiver, string methodName, string typeParams)
        {
            var arg = candidate.DuckedArgs[0];
            var parameters = candidate.OriginalParameters;
            var argName = SymbolNames.Escape(parameters[arg.ArgumentIndex].Name);

            string CallArgs(string argReplacement)
                => ForwardedCallArgs(parameters, idx => idx == arg.ArgumentIndex ? argReplacement : null);

            var localPrefix = SafeLocalPrefix("__ntf_c", TakenNames(parameters, receiver));
            EmitForwardingUnwrapBranches(sb, candidate, arg, argName, targetFullName, receiver, methodName, typeParams, CallArgs, localPrefix);

            // Direct wrap fallback; see the note in EmitDuckMethod for the cross-assembly
            // double-wrap boundary (recoverable via TryUnbox/Unbox).
            var directCall = OriginalCall(candidate, targetFullName, receiver, methodName, typeParams, CallArgs(DirectWrap(arg, argName)));
            sb.AppendLine($"                {ReturnStatement(candidate.OriginalReturnsVoid, directCall)}");
        }

        // Several ducked arguments: each argument's proxy is resolved into an interface-typed
        // local first (its unwrap branches run independently of the other arguments'), then one
        // forwarding call passes them all. Returning from inside the unwrap branches - as the
        // single-argument body does - would need a branch per combination of the arguments'
        // unwrap outcomes.
        private void EmitMultiArgForwardingBody(
            StringBuilder sb, CandidateModel candidate, string targetFullName, string receiver, string methodName, string typeParams)
        {
            var parameters = candidate.OriginalParameters;
            var taken = TakenNames(parameters, receiver);
            var unwrapPrefix = SafeLocalPrefix("__ntf_c", taken);
            var proxyPrefix = SafeLocalPrefix("__ntf_p", taken);

            var replacements = new Dictionary<int, string>();
            int unwrapCounter = 0, proxyCounter = 0;
            foreach (var arg in candidate.DuckedArgs)
            {
                var argName = SymbolNames.Escape(parameters[arg.ArgumentIndex].Name);
                replacements[arg.ArgumentIndex] = EmitArgProxyResolution(
                    sb, arg, argName, unwrapPrefix, proxyPrefix, ref unwrapCounter, ref proxyCounter);
            }

            var callArgs = ForwardedCallArgs(parameters, idx => replacements.TryGetValue(idx, out var r) ? r : null);
            var call = OriginalCall(candidate, targetFullName, receiver, methodName, typeParams, callArgs);
            sb.AppendLine($"                {ReturnStatement(candidate.OriginalReturnsVoid, call)}");
        }

        // The expression producing one ducked argument's proxy: the direct wrap when the incoming
        // value cannot be a proxy itself, otherwise a local assigned through TryUnbox branches
        // (mirroring the single-argument unwrap branches). Counters are shared across the whole
        // method body because an `out var` in an if-condition scopes to the enclosing block.
        private string EmitArgProxyResolution(
            StringBuilder sb, DuckedArgModel arg, string argName,
            string unwrapPrefix, string proxyPrefix, ref int unwrapCounter, ref int proxyCounter)
        {
            var direct = DirectWrap(arg, argName);
            if (!arg.ArgumentIsInterface || !_possibleMatches.TryGetValue(arg.InterfaceFq, out var matches) || matches.Count == 0)
                return direct;

            var local = $"{proxyPrefix}{proxyCounter++}";
            sb.AppendLine($"                {arg.InterfaceFq} {local};");
            var keyword = "if";
            foreach (var m in matches)
            {
                var unwrapped = $"{unwrapPrefix}{unwrapCounter++}";
                var proxy = ProxyFullName(m.Namespace, m.MinimalName, m.Fq, arg.InterfaceMinimalName, arg.InterfaceFq);
                sb.AppendLine($"                {keyword} ({argName}.TryUnbox<{m.Fq}>(out var {unwrapped})) {local} = new {proxy}({unwrapped});");
                keyword = "else if";
            }
            sb.AppendLine($"                else {local} = {direct};");
            return local;
        }

        private void EmitForwardingUnwrapBranches(
            StringBuilder sb, CandidateModel candidate, DuckedArgModel arg, string argName, string targetFullName, string receiver, string methodName, string typeParams,
            Func<string, string> callArgs, string localPrefix)
        {
            // Unwrap branches only make sense when the incoming value can actually be a proxy, i.e.
            // when its static type is an interface. For a concrete argument type they are dead
            // branches and force a needless box, so we skip straight to the direct wrap.
            if (!arg.ArgumentIsInterface || !_possibleMatches.TryGetValue(arg.InterfaceFq, out var matches))
                return;

            int ui = 0;
            foreach (var m in matches)
            {
                var local = $"{localPrefix}{ui++}";
                var proxy = ProxyFullName(m.Namespace, m.MinimalName, m.Fq, arg.InterfaceMinimalName, arg.InterfaceFq);
                var call = OriginalCall(candidate, targetFullName, receiver, methodName, typeParams, callArgs($"new {proxy}({local})"));
                sb.AppendLine($"                if ({argName}.TryUnbox<{m.Fq}>(out var {local})) {{");
                sb.AppendLine($"                    {(candidate.OriginalReturnsVoid ? $"{call}; return;" : $"return {call};")}");
                sb.AppendLine("                }");
            }
        }

        // The forwarding call's argument list: each ducked index replaced per `replacementFor`
        // (null = not ducked), every other parameter passed through verbatim.
        private static string ForwardedCallArgs(IReadOnlyList<ParamSig> parameters, Func<int, string?> replacementFor)
            => string.Join(", ", parameters.Select((p, idx) =>
                replacementFor(idx) ?? $"{RefArgumentPrefix(p.RefKind)}{SymbolNames.Escape(p.Name)}"));

        // The unconditional wrap of a ducked argument in its proxy; see the note in EmitDuckMethod
        // for the cross-assembly double-wrap boundary (recoverable via TryUnbox/Unbox).
        private static string DirectWrap(DuckedArgModel arg, string argName)
            => $"new {ProxyFullName(arg.UnderlyingNamespace, arg.UnderlyingMinimalName, arg.UnderlyingFq, arg.InterfaceMinimalName, arg.InterfaceFq)}(({arg.UnderlyingFq}){argName})";

        // Names a generated local must not collide with: the forwarding method's parameters and
        // the extension receiver.
        private static HashSet<string> TakenNames(IReadOnlyList<ParamSig> parameters, string receiver)
            => new HashSet<string>(parameters.Select(p => SymbolNames.Escape(p.Name)), StringComparer.Ordinal) { receiver };

        private static string OriginalCall(
            CandidateModel candidate, string targetFullName, string receiver, string methodName, string typeParams, string args)
        {
            if (candidate.OriginalIsExtensionMethod)
            {
                return $"{candidate.OriginalContainingTypeFq}.{methodName}{typeParams}({receiver}, {args})";
            }

            var callReceiver = candidate.IsStatic ? targetFullName : receiver;
            return $"{callReceiver}.{methodName}{typeParams}({args})";
        }

        private static void GenerateProxy(StringBuilder sb, ProxyDecl proxy)
        {
            var proxyTypeName = GetProxyTypeName(proxy.UnderlyingMinimalName, proxy.UnderlyingFq, proxy.InterfaceMinimalName, proxy.InterfaceFq);
            var interfaceFullName = proxy.InterfaceFq;
            var underlyingFullName = proxy.UnderlyingFq;

            // A `class`, not a `readonly struct`. A struct proxy is boxed the instant it's passed as
            // the interface, so it allocates anyway - while making a struct *underlying* impossible to
            // proxy correctly: a settable property/indexer would emit `__ntf_instance.X = value`
            // against a readonly value-type field (CS1648), and every mutating call would hit a fresh
            // defensive copy, silently losing state. A class with a mutable field allocates the same
            // (one object per call) and keeps the wrapped instance consistent for its whole lifetime.
            sb.AppendLine($"    internal sealed class {proxyTypeName} : {interfaceFullName}, IProxy<{underlyingFullName}>");
            sb.AppendLine("    {");
            // Not `readonly`: a struct underlying must stay mutable so `__ntf_instance.X = value` and
            // mutating methods compile and take effect (CS1648 otherwise).
            sb.AppendLine($"        private {underlyingFullName} __ntf_instance;");
            sb.AppendLine();
            sb.AppendLine($"        public {proxyTypeName}({underlyingFullName} instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            __ntf_instance = instance;");
            sb.AppendLine("        }");
            sb.AppendLine();
            // IProxy members are implemented explicitly so they never collide with an interface
            // member that happens to be named `Inner` or `Unwrapped`.
            sb.AppendLine($"        {underlyingFullName} IProxy<{underlyingFullName}>.Inner => __ntf_instance;");
            sb.AppendLine($"        object IProxy.Unwrapped => __ntf_instance;");
            sb.AppendLine();

            foreach (var method in proxy.MethodRequirements) EmitProxyMethod(sb, method);
            foreach (var prop in proxy.PropertyRequirements) EmitProxyProperty(sb, prop);
            foreach (var idx in proxy.IndexerRequirements) EmitProxyIndexer(sb, idx);
            foreach (var evt in proxy.EventRequirements) EmitProxyEvent(sb, evt);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitProxyMethod(StringBuilder sb, MethodSig method)
        {
            var name = SymbolNames.Escape(method.Name);
            var typeParams = method.Arity > 0 ? $"<{string.Join(", ", method.TypeParameters)}>" : "";
            var parametersStr = string.Join(", ", method.Parameters.Select(p => $"{ParamsPrefix(p)}{RefPrefix(p.RefKind)}{p.TypeFq} {SymbolNames.Escape(p.Name)}"));
            var argsStr = string.Join(", ", method.Parameters.Select(p => $"{RefArgumentPrefix(p.RefKind)}{SymbolNames.Escape(p.Name)}"));

            sb.AppendLine($"        public {method.ReturnTypeFq} {name}{typeParams}({parametersStr})");
            foreach (var constraint in method.Constraints)
            {
                if (!string.IsNullOrEmpty(constraint)) sb.AppendLine($"            {constraint}");
            }
            sb.AppendLine("        {");
            sb.AppendLine($"            {ReturnStatement(method.ReturnsVoid, $"__ntf_instance.{name}{typeParams}({argsStr})")}");
            sb.AppendLine("        }");
        }

        private static void EmitProxyProperty(StringBuilder sb, PropertySig prop)
        {
            var name = SymbolNames.Escape(prop.Name);
            sb.AppendLine($"        public {prop.TypeFq} {name}");
            sb.AppendLine("        {");
            if (prop.HasGet) sb.AppendLine($"            get => __ntf_instance.{name};");
            // Match the interface's accessor kind: an `init`-only property must be implemented with
            // `init` (CS8854 otherwise). Structural matching guarantees the underlying has a regular
            // `set` here, so forwarding `__ntf_instance.X = value` is legal.
            if (prop.HasSet) sb.AppendLine($"            {(prop.IsInit ? "init" : "set")} => __ntf_instance.{name} = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyIndexer(StringBuilder sb, IndexerSig idx)
        {
            // Indexers are positional, so the proxy renames the parameters to safe generated names.
            // This sidesteps every parameter-name hazard at once: a keyword (`@int`), a name that
            // collides with the setter's implicit `value`, etc.
            var names = idx.Parameters.Select((_, i) => $"__ntf_a{i}").ToList();
            var parametersStr = string.Join(", ", idx.Parameters.Select((p, i) => $"{RefPrefix(p.RefKind)}{p.TypeFq} {names[i]}"));
            var argsStr = string.Join(", ", idx.Parameters.Select((p, i) => $"{RefArgumentPrefix(p.RefKind)}{names[i]}"));
            sb.AppendLine($"        public {idx.TypeFq} this[{parametersStr}]");
            sb.AppendLine("        {");
            if (idx.HasGet) sb.AppendLine($"            get => __ntf_instance[{argsStr}];");
            if (idx.HasSet) sb.AppendLine($"            set => __ntf_instance[{argsStr}] = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyEvent(StringBuilder sb, EventSig evt)
        {
            var name = SymbolNames.Escape(evt.Name);
            sb.AppendLine($"        public event {evt.TypeFq} {name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            add => __ntf_instance.{name} += value;");
            sb.AppendLine($"            remove => __ntf_instance.{name} -= value;");
            sb.AppendLine("        }");
        }

        // ---------------------------------------------------------------------------------------
        // Pure string helpers
        // ---------------------------------------------------------------------------------------

        // global::-qualified so a proxy reference can never be mistaken for a member of a like-named
        // namespace, type, or (e.g.) the surrounding Duck<T> type parameter.
        private static string ProxyFullName(
            string underlyingNamespace, string underlyingMinimalName, string underlyingFq,
            string interfaceMinimalName, string interfaceFq)
            => $"global::{underlyingNamespace}.{GetProxyTypeName(underlyingMinimalName, underlyingFq, interfaceMinimalName, interfaceFq)}";

        private static string RefPrefix(RefKind refKind)
            => refKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                RefKind.RefReadOnly or RefKind.RefReadOnlyParameter => "ref readonly ",
                _ => ""
            };

        private static string RefArgumentPrefix(RefKind refKind)
            => refKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In or RefKind.RefReadOnly or RefKind.RefReadOnlyParameter => "in ",
                _ => ""
            };

        private static string DefaultSuffix(ParamSig parameter)
            => parameter.IsOptional ? $" = {parameter.DefaultValueSource ?? "default"}" : "";

        private static string ParamsPrefix(ParamSig parameter)
            => parameter.IsParams ? "params " : "";

        // A generated identifier (e.g. the extension receiver) that does not collide with any
        // user-derived name in `taken`; prepends `_` until unique. Normally returns `desired`.
        private static string SafeIdent(string desired, ICollection<string> taken)
        {
            var name = desired;
            while (taken.Contains(name)) name = "_" + name;
            return name;
        }

        // A prefix for generated locals emitted as `{prefix}0`, `{prefix}1`, ... that no name in
        // `taken` collides with. The `__ntf_*` bases are already collision-resistant; the loop
        // makes them bulletproof.
        private static string SafeLocalPrefix(string basePrefix, ICollection<string> taken)
        {
            var prefix = basePrefix;
            while (taken.Any(n => n.StartsWith(prefix, StringComparison.Ordinal) && n.Length > prefix.Length && char.IsDigit(n[prefix.Length])))
                prefix = "_" + prefix;
            return prefix;
        }

        private static string ReturnStatement(bool returnsVoid, string call)
            => returnsVoid ? $"{call};" : $"return {call};";

        // Maps an arbitrary type display name to a valid C# identifier fragment: every character
        // that isn't a letter, digit, or underscore becomes '_', and a leading digit is prefixed.
        // This keeps generic/array/nested type names (e.g. `Holder<int, string>`) from producing
        // illegal type names.
        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name)) return "_";
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        // Readable prefix (minimal names) plus a stable hash of the fully-qualified underlying and
        // interface. The prefix aids debugging; the hash guarantees uniqueness, since distinct types
        // can sanitize to the same identifier (e.g. `Foo<int>` and a type literally named `Foo_int_`,
        // or nested `Outer.Inner` and `Outer_Inner`) and would otherwise collide (CS0101).
        private static string GetProxyTypeName(
            string underlyingMinimalName, string underlyingFq, string interfaceMinimalName, string interfaceFq)
            => $"{Sanitize(underlyingMinimalName)}_{Sanitize(interfaceMinimalName)}_Proxy_{StableHash(underlyingFq + "|" + interfaceFq)}";

        // A deterministic 32-bit FNV-1a hash rendered as hex. string.GetHashCode is randomized per
        // process, which would break the generator's required determinism; this is stable across
        // runs and platforms.
        private static string StableHash(string value)
        {
            using (var sha256 = System.Security.Cryptography.SHA256.Create())
            {
                var bytes = System.Text.Encoding.UTF8.GetBytes(value);
                var hash = sha256.ComputeHash(bytes);
                var sb = new System.Text.StringBuilder(32);
                for (int i = 0; i < 16; i++)
                {
                    sb.Append(hash[i].ToString("x2"));
                }
                return sb.ToString();
            }
        }
    }
}
