using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using NTypeForge.SourceGenerator.Models;

namespace NTypeForge.SourceGenerator
{
    // Output stage (symbol-free): renders proxy structs and the per-target extension class from the
    // equatable models. The match map and interface requirements are held as fields so the many
    // emit helpers don't have to thread them through every call.
    internal sealed class ProxyEmitter
    {
        private readonly Dictionary<string, List<ConcreteInfo>> _possibleMatches;
        private readonly Dictionary<string, InterfaceInfo> _interfaceInfo;

        public ProxyEmitter(
            Dictionary<string, List<ConcreteInfo>> possibleMatches,
            Dictionary<string, InterfaceInfo> interfaceInfo)
        {
            _possibleMatches = possibleMatches;
            _interfaceInfo = interfaceInfo;
        }

        public void Emit(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            EmitProxies(context, allExtensions);
            EmitExtensions(context, allExtensions);
        }

        private void EmitProxies(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var proxiesByNamespace = new Dictionary<string, List<ProxyDecl>>(StringComparer.Ordinal);

            void AddProxy(string uFq, string uNs, string uMin, string iFq, string iMin,
                IReadOnlyList<MethodSig> mReqs,
                IReadOnlyList<PropertySig> pReqs,
                IReadOnlyList<IndexerSig> iReqs,
                IReadOnlyList<EventSig> eReqs)
            {
                if (!proxiesByNamespace.TryGetValue(uNs, out var list))
                {
                    list = new List<ProxyDecl>();
                    proxiesByNamespace[uNs] = list;
                }
                if (!list.Any(x => x.UnderlyingFq == uFq && x.InterfaceFq == iFq))
                {
                    list.Add(new ProxyDecl(uFq, uNs, uMin, iFq, iMin, mReqs, pReqs, iReqs, eReqs));
                }
            }

            foreach (var item in allExtensions)
            {
                AddProxy(item.UnderlyingFq, item.UnderlyingNamespace, item.UnderlyingMinimalName,
                    item.InterfaceFq, item.InterfaceMinimalName,
                    item.MethodRequirements, item.PropertyRequirements, item.IndexerRequirements, item.EventRequirements);
            }
            foreach (var kvp in _possibleMatches)
            {
                var iface = _interfaceInfo[kvp.Key];
                foreach (var concrete in kvp.Value)
                {
                    AddProxy(concrete.Fq, concrete.Namespace, concrete.MinimalName,
                        iface.Fq, iface.MinimalName,
                        iface.MethodRequirements, iface.PropertyRequirements, iface.IndexerRequirements, iface.EventRequirements);
                }
            }

            foreach (var kvp in proxiesByNamespace.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {kvp.Key}");
                sb.AppendLine("{");
                foreach (var proxy in kvp.Value.OrderBy(x => x.UnderlyingFq + "|" + x.InterfaceFq, StringComparer.Ordinal))
                {
                    GenerateProxyStruct(sb, proxy);
                }
                sb.AppendLine("}");
                context.AddSource($"{kvp.Key.Replace(".", "_")}_Proxies.g.cs", sb.ToString());
            }
        }

        private void EmitExtensions(SourceProductionContext context, List<CandidateModel> allExtensions)
        {
            var extensionsByTarget = new Dictionary<string, List<CandidateModel>>(StringComparer.Ordinal);
            foreach (var item in allExtensions)
            {
                if (!extensionsByTarget.TryGetValue(item.TargetFq, out var list))
                {
                    list = new List<CandidateModel>();
                    extensionsByTarget[item.TargetFq] = list;
                }
                list.Add(item);
            }

            foreach (var kvp in extensionsByTarget.OrderBy(k => k.Key, StringComparer.Ordinal))
            {
                // Order by a location-independent content key so the emitted Duck<T> branches and
                // forwarding methods don't depend on the order the duck sites appear in source.
                var items = kvp.Value.OrderBy(EmitOrderKey, StringComparer.Ordinal).ToList();
                var first = items[0];
                var targetNamespace = first.TargetNamespace;
                var targetFullName = first.TargetFq;
                var extensionClassName = $"{Sanitize(first.TargetMinimalName)}_DuckTypingExtensions";

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                sb.AppendLine("using NTypeForge;");
                sb.AppendLine();
                sb.AppendLine($"namespace {targetNamespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    public static class {extensionClassName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        extension ({targetFullName} target)");
                sb.AppendLine("        {");

                EmitDuckMethod(sb, items);
                EmitForwardingMethods(sb, items, targetFullName);

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                // Qualify the hint with the target namespace: two target types with the same simple
                // name in different namespaces would otherwise produce the same hint name and crash
                // the generator (duplicate hintName).
                context.AddSource($"{targetNamespace.Replace(".", "_")}_{extensionClassName}.g.cs", sb.ToString());
            }
        }

        // Stable, location-independent ordering key for a candidate's emitted contribution: the
        // forwarded method name + parameter shape, then the interface and underlying types. Duck
        // calls (empty method name / parameters) collapse to ordering by interface.
        private static string EmitOrderKey(CandidateModel c)
            => string.Join("|",
                c.OriginalMethodName,
                string.Join(",", c.OriginalParameters.Select(p => p.Key)),
                c.ArgumentFq,
                c.InterfaceFq,
                c.UnderlyingFq);

        // Emit a single Duck<T>() per target type that dispatches on typeof(T). One method per
        // interface would share the identical Duck<T>() signature (return type and generic
        // constraints don't participate in overloading) and collide with CS0111 when a type is
        // ducked to more than one interface.
        private void EmitDuckMethod(StringBuilder sb, List<CandidateModel> items)
        {
            var duckCandidates = new List<CandidateModel>();
            var seenDuckInterfaces = new HashSet<string>(StringComparer.Ordinal);
            foreach (var item in items)
            {
                if (item.IsDuckCall && seenDuckInterfaces.Add(item.InterfaceFq))
                    duckCandidates.Add(item);
            }

            if (duckCandidates.Count == 0) return;

            sb.AppendLine("            public T Duck<T>() where T : class");
            sb.AppendLine("            {");
            foreach (var candidate in duckCandidates)
            {
                var iface = candidate.InterfaceFq;
                sb.AppendLine($"                if (typeof(T) == typeof({iface}))");
                sb.AppendLine("                {");
                // Unwrap check: only when target is an interface can it actually be a proxy that
                // needs re-wrapping. For a concrete target the unwrap branch is always trivially
                // taken, so we skip it and wrap directly.
                if (candidate.TargetIsInterface && _possibleMatches.TryGetValue(iface, out var matches))
                {
                    int ui = 0;
                    foreach (var m in matches)
                    {
                        var local = $"c_{ui++}";
                        sb.AppendLine($"                    if (target.TryUnbox<{m.Fq}>(out var {local})) return (T)(object)new {ProxyFullName(m.Namespace, m.MinimalName, candidate.InterfaceMinimalName)}({local});");
                    }
                }
                // Direct wrap. Unreachable for a proxy whose concrete type was ducked in this
                // compilation (its TryUnbox branch above wins). It only fires for a non-proxy or
                // for a proxy whose concrete is unknown here (e.g. created in another assembly); in
                // the latter case this double-wraps, but TryUnbox/Unbox still walk the full chain
                // back to the original instance, so only single-level IProxy<T>.Inner is affected.
                sb.AppendLine($"                    return (T)(object)new {ProxyFullName(candidate.UnderlyingNamespace, candidate.UnderlyingMinimalName, candidate.InterfaceMinimalName)}(({candidate.UnderlyingFq})target);");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                throw new global::System.InvalidOperationException(\"NTypeForge: no proxy was generated for \" + typeof(T));");
            sb.AppendLine("            }");
        }

        private void EmitForwardingMethods(StringBuilder sb, List<CandidateModel> items, string targetFullName)
        {
            var generatedMethods = new HashSet<string>(StringComparer.Ordinal);

            foreach (var candidate in items)
            {
                if (candidate.IsDuckCall) continue;
                EmitForwardingMethod(sb, candidate, targetFullName, generatedMethods);
            }
        }

        private void EmitForwardingMethod(
            StringBuilder sb, CandidateModel candidate, string targetFullName, HashSet<string> generatedMethods)
        {
            var argIndex = candidate.ArgumentIndex;
            var parameters = candidate.OriginalParameters;
            var argName = parameters[argIndex].Name;
            var receiver = candidate.IsStatic ? targetFullName : "target";
            var methodName = candidate.OriginalMethodName;

            // The forwarding call's argument list, with the duck-typed argument replaced by
            // `argReplacement` and every other parameter passed through verbatim.
            string CallArgs(string argReplacement) => string.Join(", ", parameters.Select((p, idx) =>
                idx == argIndex ? argReplacement : $"{RefPrefix(p.RefKind)}{p.Name}"));

            var methodParams = string.Join(", ", parameters.Select((p, idx) =>
                $"{RefPrefix(p.RefKind)}{(idx == argIndex ? candidate.ArgumentFq : p.TypeFq)} {p.Name}"));

            var methodSig = $"{methodName}({methodParams})";
            if (!generatedMethods.Add(methodSig)) return;

            var isStatic = candidate.IsStatic ? "static " : "";
            sb.AppendLine($"            public {isStatic}{candidate.OriginalReturnTypeFq} {methodName}({methodParams})");
            sb.AppendLine("            {");

            EmitForwardingUnwrapBranches(sb, candidate, argName, receiver, methodName, CallArgs);

            // Direct wrap fallback; see the note in EmitDuckMethod for the cross-assembly
            // double-wrap boundary (recoverable via TryUnbox/Unbox).
            var directProxy = ProxyFullName(candidate.UnderlyingNamespace, candidate.UnderlyingMinimalName, candidate.InterfaceMinimalName);
            var directCall = $"{receiver}.{methodName}({CallArgs($"new {directProxy}(({candidate.UnderlyingFq}){argName})")})";
            sb.AppendLine($"                {ReturnStatement(candidate.OriginalReturnsVoid, directCall)}");
            sb.AppendLine("            }");
        }

        private void EmitForwardingUnwrapBranches(
            StringBuilder sb, CandidateModel candidate, string argName, string receiver, string methodName,
            Func<string, string> callArgs)
        {
            // Unwrap branches only make sense when the incoming value can actually be a proxy, i.e.
            // when its static type is an interface. For a concrete argument type they are dead
            // branches and force a needless box, so we skip straight to the direct wrap.
            if (!candidate.ArgumentIsInterface || !_possibleMatches.TryGetValue(candidate.InterfaceFq, out var matches))
                return;

            int ui = 0;
            foreach (var m in matches)
            {
                var local = $"c_{ui++}";
                var proxy = ProxyFullName(m.Namespace, m.MinimalName, candidate.InterfaceMinimalName);
                var call = $"{receiver}.{methodName}({callArgs($"new {proxy}({local})")})";
                sb.AppendLine($"                if ({argName}.TryUnbox<{m.Fq}>(out var {local})) {{");
                sb.AppendLine($"                    {(candidate.OriginalReturnsVoid ? $"{call}; return;" : $"return {call};")}");
                sb.AppendLine("                }");
            }
        }

        private static void GenerateProxyStruct(StringBuilder sb, ProxyDecl proxy)
        {
            var structName = GetProxyStructName(proxy.UnderlyingMinimalName, proxy.InterfaceMinimalName);
            var interfaceFullName = proxy.InterfaceFq;
            var underlyingFullName = proxy.UnderlyingFq;

            sb.AppendLine($"    internal readonly struct {structName} : {interfaceFullName}, IProxy<{underlyingFullName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {underlyingFullName} _instance;");
            sb.AppendLine();
            sb.AppendLine($"        public {structName}({underlyingFullName} instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            _instance = instance;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {underlyingFullName} Inner => _instance;");
            sb.AppendLine($"        object IProxy.Unwrapped => _instance;");
            sb.AppendLine();

            foreach (var method in proxy.MethodRequirements) EmitProxyMethod(sb, method);
            foreach (var prop in proxy.PropertyRequirements) EmitProxyProperty(sb, prop);
            foreach (var idx in proxy.IndexerRequirements) EmitProxyIndexer(sb, idx);
            foreach (var evt in proxy.EventRequirements) EmitProxyEvent(sb, evt);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitProxyMethod(StringBuilder sb, MethodSig method)
        {
            var typeParams = method.Arity > 0 ? $"<{string.Join(", ", method.TypeParameters)}>" : "";
            var parametersStr = string.Join(", ", method.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{p.TypeFq} {p.Name}"));
            var argsStr = string.Join(", ", method.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{p.Name}"));

            sb.AppendLine($"        public {method.ReturnTypeFq} {method.Name}{typeParams}({parametersStr})");
            foreach (var constraint in method.Constraints)
            {
                if (!string.IsNullOrEmpty(constraint)) sb.AppendLine($"            {constraint}");
            }
            sb.AppendLine("        {");
            sb.AppendLine($"            {ReturnStatement(method.ReturnsVoid, $"_instance.{method.Name}{typeParams}({argsStr})")}");
            sb.AppendLine("        }");
        }

        private static void EmitProxyProperty(StringBuilder sb, PropertySig prop)
        {
            sb.AppendLine($"        public {prop.TypeFq} {prop.Name}");
            sb.AppendLine("        {");
            if (prop.HasGet) sb.AppendLine($"            get => _instance.{prop.Name};");
            // Match the interface's accessor kind: an `init`-only property must be implemented with
            // `init` (CS8854 otherwise). Structural matching guarantees the underlying has a regular
            // `set` here, so forwarding `_instance.X = value` is legal.
            if (prop.HasSet) sb.AppendLine($"            {(prop.IsInit ? "init" : "set")} => _instance.{prop.Name} = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyIndexer(StringBuilder sb, IndexerSig idx)
        {
            var parametersStr = string.Join(", ", idx.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{p.TypeFq} {p.Name}"));
            var argsStr = string.Join(", ", idx.Parameters.Select(p => $"{RefPrefix(p.RefKind)}{p.Name}"));
            sb.AppendLine($"        public {idx.TypeFq} this[{parametersStr}]");
            sb.AppendLine("        {");
            if (idx.HasGet) sb.AppendLine($"            get => _instance[{argsStr}];");
            if (idx.HasSet) sb.AppendLine($"            set => _instance[{argsStr}] = value;");
            sb.AppendLine("        }");
        }

        private static void EmitProxyEvent(StringBuilder sb, EventSig evt)
        {
            sb.AppendLine($"        public event {evt.TypeFq} {evt.Name}");
            sb.AppendLine("        {");
            sb.AppendLine($"            add => _instance.{evt.Name} += value;");
            sb.AppendLine($"            remove => _instance.{evt.Name} -= value;");
            sb.AppendLine("        }");
        }

        // ---------------------------------------------------------------------------------------
        // Pure string helpers
        // ---------------------------------------------------------------------------------------

        // global::-qualified so a proxy reference can never be mistaken for a member of a like-named
        // namespace, type, or (e.g.) the surrounding Duck<T> type parameter.
        private static string ProxyFullName(string underlyingNamespace, string underlyingMinimalName, string interfaceMinimalName)
            => $"global::{underlyingNamespace}.{GetProxyStructName(underlyingMinimalName, interfaceMinimalName)}";

        private static string RefPrefix(RefKind refKind)
            => refKind switch { RefKind.Ref => "ref ", RefKind.Out => "out ", RefKind.In => "in ", _ => "" };

        private static string ReturnStatement(bool returnsVoid, string call)
            => returnsVoid ? $"{call};" : $"return {call};";

        // Maps an arbitrary type display name to a valid C# identifier fragment: every character
        // that isn't a letter, digit, or underscore becomes '_', and a leading digit is prefixed.
        // This keeps generic/array/nested type names (e.g. `Holder<int, string>`) from producing
        // illegal struct names.
        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name)) return "_";
            var sb = new StringBuilder(name.Length);
            foreach (var ch in name)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }

        private static string GetProxyStructName(string underlyingMinimalName, string interfaceMinimalName)
            => $"{Sanitize(underlyingMinimalName)}_{Sanitize(interfaceMinimalName)}_Proxy";
    }
}
